title: Tiber AI Community
description: Deploy and run LLM models on Intel Data Center GPUs
baseurl: "ai-templates"
url: "https://tiberaicommunity.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag 
