title: Tiber AI Community
description: Deploy and run AI models on Intel Tiber AI cloud
baseurl: "ai-templates"
url: "https://tiberaicommunity.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag 
